from .init_dialogs_controller import InitDialogsController
from .main_window_controller import MainWindowController
from .settings_window_controller import SettingsWindowController
from .restriction_dialog_controller import RestrictionWindowController
from .plugin_controller import PluginController